version = "0.2.X"
defaultTheme = "auto"
gitRepo = "https://github.com/antoinemartin/antoinemartin.github.io"
paginate = 20
dateFormat = "02-01"

[author]
name = "Antoine Martin"
email = "antoine@mrtn.me"
link = "https://linked.in/in/antoinemartin"

[section]
paginate = 20
dateFormat = "02-01"

[list]
paginate = 20
dateFormat = "02-01"

[header.title]
name = 'mrtn.me'

[footer]
enable = true
hugo = true
copyright = true
author = true
since = 2012
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[page]
hiddenFromHomePage = false
hiddenFromSearch = false
twemoji = false
lightgallery = false
ruby = true
fraction = true
fontawesome = true
linkToMarkdown = true
rssFullText = false

[page.toc]
enable = false
keepStatic = false
auto = true

[page.code]
copy = true
maxShownLines = 30

[page.comment]
enable = true

[page.comment.disqus]
enable = true
shortname = "geekquickies"


[analytics]
enable = true
[analytics.google]
id = "UA-29953512-1"
anonymizeIP = false

[home]
rss = 10
[home.profile]
enable = true
# gravatarEmail = "antoine@openance.com"
avatarURL = "/images/avatar.webp"
title = "mrtn.me"
subtitle = "Stories from the cloudvergence"
typeit = true
social = true
disclaimer = ""
[home.posts]
enable = true
paginate = 6
defaultHiddenFromHomePage = false

[social]
GitHub = "antoinemartin"
Linkedin = "antoinemartin"
X = "antoinemartin"
RSS = true

[search]
enable = true
# type of search engine ("lunr", "algolia")
type = "lunr"
# max index length of the chunked content
contentLength = 4000
# placeholder of the search bar
placeholder = ""
# max number of results length
maxResultLength = 10
# snippet length of the result
snippetLength = 30
# HTML tag name of the highlight part in results
highlightTag = "em"
# whether to use the absolute URL based on the baseURL in search index
absoluteURL = false
[search.algolia]
index = ""
appID = ""
searchKey = ""
